const STORAGE_KEY="study-quest-v1";
const seed={xp:120,streak:2,lastStudyDate:"",tasks:[
{id:1,subject:"算数",book:"テーマ教材",unit:"単位換算",level:"A",number:"No.8",priority:93,status:"直し待ち",nextReview:"today",mastered:false,lastResult:null,miss:"単位"},
{id:2,subject:"算数",book:"演習教材",unit:"約数",level:"A",number:"No.4",priority:90,status:"理解不十分",nextReview:"today",mastered:false,lastResult:null,miss:"同じ誤り"},
{id:3,subject:"国語",book:"国語テキスト",unit:"物語文・心情",level:"A",number:"問3",priority:82,status:"再確認",nextReview:"today",mastered:false,lastResult:null,miss:"根拠不足"},
{id:4,subject:"算数",book:"演習教材",unit:"図形",level:"B",number:"No.13",priority:68,status:"再確認",nextReview:"today",mastered:false,lastResult:null,miss:"図・条件整理"},
{id:5,subject:"理科",book:"理科テキスト",unit:"人体",level:"A",number:"No.7",priority:61,status:"3日後確認",nextReview:"today",mastered:false,lastResult:null,miss:"知識不足"},
{id:6,subject:"国語",book:"国語テキスト",unit:"物語文・理由説明",level:"A",number:"問4",priority:52,status:"3日後確認",nextReview:"future",mastered:false,lastResult:null,miss:"自分の解釈優先"},
{id:7,subject:"社会",book:"社会テキスト",unit:"地理",level:"B",number:"No.15",priority:39,status:"定着確認待ち",nextReview:"future",mastered:false,lastResult:null,miss:"知識不足"},
{id:8,subject:"算数",book:"演習教材",unit:"速さ",level:"A",number:"No.6",priority:25,status:"定着",nextReview:"future",mastered:true,lastResult:"excellent",miss:"ケアレス"}],history:[]};
let state=loadState(),activeTaskId=null,filterSubject="すべて";
function cloneSeed(){return JSON.parse(JSON.stringify(seed))}
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw):cloneSeed()}catch(e){return cloneSeed()}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function todayKey(){const d=new Date();const y=d.getFullYear();const m=String(d.getMonth()+1).padStart(2,"0");const day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`}
function getLevel(){return Math.max(1,Math.floor(state.xp/100)+1)}
function todaysTasks(){return state.tasks.filter(t=>t.nextReview==="today"&&!t.mastered)}
function escapeHTML(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function taskCard(t,compact=false){const doneToday=state.history.some(h=>h.taskId===t.id&&h.date===todayKey());return `<div class="task card"><div class="task-main"><div class="task-topline"><span class="subject ${t.subject}">${t.subject}</span><span class="level">${t.level}レベル</span><span class="priority">優先 ${t.priority}</span></div><p class="task-title">${escapeHTML(t.unit)} ${escapeHTML(t.number)}</p><div class="task-meta">${escapeHTML(t.book||"")} ・ ${escapeHTML(t.status)}</div></div>${doneToday?`<span class="done-tag">今日できた</span>`:`<button class="start-btn" data-task="${t.id}">${compact?"やる":"結果"}</button>`}</div>`}
function render(){const today=todaysTasks();const doneCount=today.filter(t=>state.history.some(h=>h.taskId===t.id&&h.date===todayKey())).length;document.querySelector("#todayDone").textContent=doneCount;document.querySelector("#todayTotal").textContent=today.length;document.querySelector("#todayProgress").style.width=`${today.length?(doneCount/today.length)*100:100}%`;document.querySelector("#homeMessage").textContent=today.length===0?"今日は復習対象なし。ゆっくり休もう。":doneCount===today.length?"今日のクエスト、ぜんぶクリア！":"上から1問ずつでOK。";document.querySelector("#level").textContent=getLevel();document.querySelector("#xp").textContent=state.xp;document.querySelector("#streak").textContent=state.streak;document.querySelector("#roomLevel").textContent=`Lv.${getLevel()}`;const sortedToday=[...today].sort((a,b)=>b.priority-a.priority);document.querySelector("#topTasks").innerHTML=sortedToday.slice(0,4).map(t=>taskCard(t,true)).join("")||`<div class="empty card">今日の復習対象はありません。</div>`;const filtered=state.tasks.filter(t=>filterSubject==="すべて"||t.subject===filterSubject).sort((a,b)=>(a.mastered-b.mastered)||b.priority-a.priority);document.querySelector("#allTasks").innerHTML=filtered.map(t=>taskCard(t,false)).join("")||`<div class="empty card">まだ問題がありません。</div>`;renderGrowth();renderParent();bindTaskButtons()}
function renderGrowth(){const level=getLevel();document.querySelector("#unlockShelf").style.opacity=level>=2?"1":"0";document.querySelector("#unlockCushion").style.opacity=level>=3?"1":"0";document.querySelector("#unlockPlant").style.opacity=level>=4?"1":"0";const unlocks=[{level:2,icon:"📚",name:"本棚"},{level:3,icon:"☁",name:"ふわふわクッション"},{level:4,icon:"🌿",name:"観葉植物"},{level:5,icon:"✨",name:"きらきらライト"}];const next=unlocks.find(u=>u.level>level)||{level:level+1,icon:"🎁",name:"ひみつのごほうび"};const targetXp=(next.level-1)*100,prevXp=Math.max(0,(next.level-2)*100),pct=Math.max(0,Math.min(100,((state.xp-prevXp)/(targetXp-prevXp))*100));document.querySelector("#nextUnlock").innerHTML=`<div class="unlock-row"><div class="unlock-icon">${next.icon}</div><div class="unlock-bar"><strong>Lv.${next.level} ${next.name}</strong><div class="progress"><div style="width:${pct}%"></div></div><div class="mini-copy">あと ${Math.max(0,targetXp-state.xp)} XP</div></div></div>`;const hasHistory=state.history.length>0,aExcellent=state.tasks.some(t=>t.level==="A"&&(t.mastered||t.lastResult==="excellent"));document.querySelector("#badgeFirst").classList.toggle("unlocked",hasHistory);document.querySelector("#badgeStreak").classList.toggle("unlocked",state.streak>=3);document.querySelector("#badgeMaster").classList.toggle("unlocked",aExcellent)}
function renderParent(){const redo=state.tasks.filter(t=>!t.mastered&&["直し待ち","理解不十分"].includes(t.status)).length,aPending=state.tasks.filter(t=>t.level==="A"&&!t.mastered).length,mastered=state.tasks.filter(t=>t.mastered).length;document.querySelector("#metricRedo").textContent=redo;document.querySelector("#metricA").textContent=aPending;document.querySelector("#metricToday").textContent=todaysTasks().length;document.querySelector("#metricMastered").textContent=mastered;const groups={};state.tasks.filter(t=>!t.mastered).forEach(t=>{const key=`${t.subject}・${t.unit}`;if(!groups[key])groups[key]={count:0,score:0};groups[key].count++;groups[key].score+=t.priority});const weak=Object.entries(groups).map(([name,v])=>({name,score:Math.round(v.score/v.count),count:v.count})).sort((a,b)=>b.score-a.score).slice(0,5);document.querySelector("#weakUnits").innerHTML=weak.length?weak.map(w=>`<div class="weak-row"><div><strong>${escapeHTML(w.name)}</strong><div class="mini-copy">未完了 ${w.count}問</div></div><div class="weak-score">${w.score}</div></div>`).join(""):`<div class="empty">要注意単元はありません。</div>`}
function bindTaskButtons(){document.querySelectorAll("[data-task]").forEach(btn=>{btn.onclick=()=>{activeTaskId=Number(btn.dataset.task);const t=state.tasks.find(x=>x.id===activeTaskId);document.querySelector("#resultTaskTitle").textContent=`${t.subject} ${t.unit} ${t.number}`;document.querySelector("#resultDialog").showModal()}})}
document.querySelectorAll(".nav-btn").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".nav-btn").forEach(b=>b.classList.remove("active"));document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));btn.classList.add("active");document.querySelector(`#${btn.dataset.view}`).classList.add("active");window.scrollTo({top:0,behavior:"smooth"})}));
document.querySelectorAll("#subjectFilters .chip").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll("#subjectFilters .chip").forEach(b=>b.classList.remove("active"));btn.classList.add("active");filterSubject=btn.dataset.subject;render()}));
document.querySelectorAll("[data-result]").forEach(btn=>btn.addEventListener("click",e=>{e.preventDefault();applyResult(btn.dataset.result);document.querySelector("#resultDialog").close()}));
function applyResult(result){const t=state.tasks.find(x=>x.id===activeTaskId);if(!t)return;const xpMap={excellent:20,good:15,hint:8,wrong:3};if(result==="excellent"){t.status="定着";t.nextReview="future";t.mastered=true}else if(result==="good"){t.status="1週間後確認";t.nextReview="future";t.mastered=false}else if(result==="hint"){t.status="3日後確認";t.nextReview="future";t.mastered=false}else{t.status="直し待ち";t.nextReview="today";t.mastered=false}t.lastResult=result;const bonus=t.level==="A"&&result==="excellent"?5:0;state.xp+=xpMap[result]+bonus;state.history.push({taskId:t.id,date:todayKey(),result,xp:xpMap[result]+bonus});updateStreak();saveState();showToast(`+${xpMap[result]+bonus} XP！`);render()}
function updateStreak(){const today=todayKey();if(state.lastStudyDate===today)return;if(!state.lastStudyDate){state.streak=Math.max(1,state.streak)}else{const prev=new Date(state.lastStudyDate+"T00:00:00"),now=new Date(today+"T00:00:00"),diff=Math.round((now-prev)/86400000);state.streak=diff===1?state.streak+1:1}state.lastStudyDate=today}
document.querySelector("#addTaskBtn").onclick=()=>document.querySelector("#taskDialog").showModal();document.querySelector("#taskForm").addEventListener("submit",e=>{e.preventDefault();const fd=new FormData(e.currentTarget),newId=Math.max(0,...state.tasks.map(t=>t.id))+1;state.tasks.push({id:newId,subject:fd.get("subject"),book:fd.get("book")||"",unit:fd.get("unit"),level:fd.get("level"),number:fd.get("number"),priority:fd.get("level")==="A"?70:fd.get("level")==="B"?50:30,status:"未着手",nextReview:"today",mastered:false,lastResult:null,miss:""});saveState();e.currentTarget.reset();document.querySelector("#taskDialog").close();render();showToast("クエストを追加しました")});
document.querySelector("#installHelpBtn").onclick=()=>document.querySelector("#helpDialog").showModal();
document.querySelector("#exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`study-quest-backup-${todayKey()}.json`;a.click();URL.revokeObjectURL(a.href)};
document.querySelector("#importInput").addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;try{const parsed=JSON.parse(await f.text());if(!parsed.tasks||!Array.isArray(parsed.tasks))throw new Error("invalid");state=parsed;saveState();render();showToast("バックアップを読み込みました")}catch(err){alert("バックアップファイルを読み込めませんでした。")}e.target.value=""});
document.querySelector("#resetBtn").onclick=()=>{if(confirm("試作データに戻します。現在の記録は消えます。よろしいですか？")){state=cloneSeed();saveState();render();showToast("試作データに戻しました")}};
function showToast(msg){const el=document.querySelector("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(showToast.t);showToast.t=setTimeout(()=>el.classList.remove("show"),1800)}
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));render();
